### PR TITLE
fix: DateField/DateTimeField isEqual

### LINKED ISSUE #157: DateTimeField/DateField isEqual
Current these fields don't do equality checks on `Date` objects. We probably should:

```
    isEqual(a?: Date, b?: Date): boolean {
        if (!a || !b) {
            return false;
        }
        return a === b || a.getTime() === b.getTime();
    }
```

### PR DESCRIPTION
**Pull request by davecoates**
- DateField and DateTimeField now consider dates that represent the same
  date or datetime as equal
- This is important for caching otherwise a record with these fields will
  never be considered equal (eg. when record comes from API endpoint via
  viewModelCachingMiddleware it will construct an instance of the viewmodel
  then do an isEqual check to see if it differs from existing record)

Resolves #157

### CODE REVIEW

File: js-packages/@prestojs/viewmodel/src/fields/DateField.ts [hunk 1]
```diff
@@ -21,6 +21,19 @@ export default class DateField extends Field<Date, string | Date> {
         return new Date(value);
     }
 
+    isEqual(a?: Date, b?: Date): boolean {
+        if (!a || !b) {
+            return false;
```
Comment (fanglong-alliance) [inline js-packages/@prestojs/viewmodel/src/fields/DateField.ts:29]: should it be considered equal if both values are none?

**Comment by fanglong-alliance** [comment]
otherwise lgtm

File: js-packages/@prestojs/viewmodel/src/fields/DateField.ts (hunk 1 above)
Comment (davecoates) [reply js-packages/@prestojs/viewmodel/src/fields/DateField.ts:29]: 🤦‍♂️  thank you - definitely
